### ISSUE TITLE
Permanent single node

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum-prototype#53]
**Description**

Currently the Pendulum UI gets reset after certain interval of time. To avoid this we need to have  a Permanent single node.

**Comment by TorstenStueber** [comment]
Figure out whether this is possible with Google Cloud run (whether it is possible to have permanent deployments). If yes, then use Google Cloud run, otherwise use Google Container Engine.

Probably we need to use a volume to store the data permanently – figure out how to set this up with Substrate (maybe on the command line).

**Comment by gonzamontiel** [comment]
According to this https://blog.sivamuthukumar.com/google-cloud-run-add-persistent-storage, we have 3 options to connect a permanent storage to Cloud run, nevertheless, my perception is that this is not the right support for our node. We would likely need another solution like Google Container.

> Cloud SQL - Storing Structured Data
> Cloud Firestore - Storing Unstructured Data
> Cloud Storage - Storing files such as images and video

I will research solutions with Container Engine or Google Cloud Anthos

**Comment by gonzamontiel** [comment]
Node deployed to gcloud.
